using System.Resources;

namespace PangeaShellApp.Resources;

/// <summary>
/// Exposes the compiled <c>Strings.resx</c> to the localization feature, which looks for a type
/// with a public static <see cref="System.Resources.ResourceManager"/> property.
/// </summary>
/// <remarks>
/// Hand-written rather than generated by the .resx designer: the designer emits one property per
/// key, and nothing here reads the keys that way - <c>LocalizedStrings</c>
/// resolves them by name so a view can name its own.
/// </remarks>
public static class Strings
{
    public static ResourceManager ResourceManager { get; } =
        new("PangeaShellApp.Resources.Strings", typeof(Strings).Assembly);
}
