using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CdCSharp.Pangea.Binding.CodeGeneration;

/// <summary>
/// Generador de código profesional que utiliza análisis funcional completo
/// para generar propiedades con notificaciones automáticas optimizadas
/// </summary>
[Generator]
public class ViewModelSourceGenerator : IIncrementalGenerator
{
    private const string GENERATOR_VERSION = "v2.1.0";
    private const string BUILD_DATE = "2025-08-30";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ViewModelAnalysis?> viewModelAnalyses = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsCandidateViewModel(s),
                static (ctx, _) => AnalyzeViewModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(viewModelAnalyses, static (spc, analysis) => GenerateCode(analysis, spc));
    }

    private static bool IsCandidateViewModel(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl &&
               (HasBindingFields(classDecl) || HasCommandProperties(classDecl));
    }

    private static bool HasBindingFields(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members.OfType<FieldDeclarationSyntax>()
            .Any(f => f.AttributeLists.Any(al =>
                al.Attributes.Any(a => a.Name.ToString().Contains("Binding"))));
    }

    private static bool HasCommandProperties(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members.OfType<PropertyDeclarationSyntax>()
            .Any(p => p.Type.ToString().Contains("RelayCommand"));
    }

    private static ViewModelAnalysis? AnalyzeViewModel(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration) return null;

        FunctionalAnalyzer analyzer = new FunctionalAnalyzer();
        return analyzer.AnalyzeViewModel(classDeclaration, context.SemanticModel);
    }

    private static void GenerateCode(ViewModelAnalysis? analysis, SourceProductionContext context)
    {
        if (analysis == null || analysis.BindingFields.Count == 0) return;

        string source = GenerateClassSource(analysis);
        context.AddSource($"{analysis.ClassName}.Binding.g.cs", SourceText.From(source, Encoding.UTF8));

        // Generar archivo de debug con información del análisis (solo en DEBUG)
#if DEBUG
        string debugInfo = GenerateDebugInfo(analysis);
        context.AddSource($"{analysis.ClassName}.Analysis.Debug.g.cs", SourceText.From(debugInfo, Encoding.UTF8));
#endif
    }

    private static string GenerateClassSource(ViewModelAnalysis analysis)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine(
            $"// Generated by Pangea Binding Feature with Professional Functional Analysis {GENERATOR_VERSION}");
        sb.AppendLine($"// Build Date: {BUILD_DATE}");
        sb.AppendLine("// This file contains optimized property implementations with automatic notifications");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();
        sb.AppendLine($"namespace {analysis.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {analysis.ClassName}");
        sb.AppendLine("{");

        // Generar propiedades con análisis funcional completo
        foreach (BindingFieldInfo field in analysis.BindingFields)
        {
            GenerateOptimizedProperty(sb, field, analysis);
        }

        // Generar declaraciones de métodos parciales
        foreach (BindingFieldInfo field in analysis.BindingFields.Where(f => !f.ReadOnly))
        {
            sb.AppendLine($"    partial void On{field.PropertyName}Changed();");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateOptimizedProperty(StringBuilder sb, BindingFieldInfo field, ViewModelAnalysis analysis)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets or sets {field.PropertyName}");
        if (analysis.NotificationRequirements.TryGetValue(field.PropertyName,
                out NotificationRequirements? requirements))
        {
            int totalNotifications = requirements.ComputedPropertyNotifications.Count +
                                     requirements.CommandNotifications.Count +
                                     requirements.CollectionDependentNotifications.Count;
            if (totalNotifications > 0)
            {
                sb.AppendLine(
                    $"    /// Automatically triggers {totalNotifications} dependent notifications when changed");
            }
        }

        sb.AppendLine($"    /// </summary>");

        sb.AppendLine($"    public {field.FieldType} {field.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {field.FieldName};");

        if (!field.ReadOnly)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (SetProperty(ref {field.FieldName}, value))");
            sb.AppendLine("            {");

            // Llamar método parcial
            sb.AppendLine($"                On{field.PropertyName}Changed();");

            // Generar notificaciones basadas en análisis funcional
            if (requirements != null)
            {
                GenerateComputedPropertyNotifications(sb, requirements.ComputedPropertyNotifications);
                GenerateCommandNotifications(sb, requirements.CommandNotifications);
                GenerateCollectionDependentNotifications(sb, requirements.CollectionDependentNotifications);
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateComputedPropertyNotifications(StringBuilder sb, List<string> computedProperties)
    {
        if (!computedProperties.Any()) return;

        sb.AppendLine();
        sb.AppendLine("                // Computed property notifications");

        foreach (string computedProp in computedProperties.OrderBy(cp => cp))
        {
            sb.AppendLine($"                OnPropertyChanged(nameof({computedProp}));");
        }
    }

    private static void GenerateCommandNotifications(StringBuilder sb, List<string> commandNotifications)
    {
        if (commandNotifications.Any())
        {
            sb.AppendLine();
            sb.AppendLine("                // Command CanExecute notifications");
            foreach (string commandName in commandNotifications.OrderBy(c => c))
            {
                sb.AppendLine($"                {commandName}.RaiseCanExecuteChanged();");
            }
        }
    }

    private static void GenerateCollectionDependentNotifications(StringBuilder sb, List<string> collectionNotifications)
    {
        if (!collectionNotifications.Any()) return;

        sb.AppendLine();
        sb.AppendLine("                // Collection-dependent notifications");

        foreach (string notification in collectionNotifications.OrderBy(n => n))
        {
            sb.AppendLine($"                OnPropertyChanged(nameof({notification}));");
        }
    }

#if DEBUG
    private static string GenerateDebugInfo(ViewModelAnalysis analysis)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("/*");
        sb.AppendLine($" * DEBUG: Functional Analysis Report {GENERATOR_VERSION}");
        sb.AppendLine($" * Class: {analysis.ClassName}");
        sb.AppendLine($" * Generated: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($" * Build Date: {BUILD_DATE}");
        sb.AppendLine(" * ===================================");
        sb.AppendLine();

        sb.AppendLine(" * BINDING FIELDS:");
        foreach (BindingFieldInfo binding in analysis.BindingFields)
        {
            sb.AppendLine($" *   {binding.PropertyName} ({binding.FieldType}) - ReadOnly: {binding.ReadOnly}");
        }

        sb.AppendLine();

        sb.AppendLine(" * COMPUTED PROPERTIES:");
        foreach (ComputedPropertyInfo computed in analysis.ComputedProperties)
        {
            sb.AppendLine($" *   {computed.PropertyName}:");
            sb.AppendLine($" *     Dependencies: [{string.Join(", ", computed.DirectDependencies)}]");
        }

        sb.AppendLine();

        sb.AppendLine(" * CAN EXECUTE METHODS/PROPERTIES:");
        foreach (CanExecuteMethodInfo canExecute in analysis.CanExecuteMethods)
        {
            sb.AppendLine($" *   {canExecute.MethodName}:");
            sb.AppendLine($" *     Dependencies: [{string.Join(", ", canExecute.DirectDependencies)}]");
        }

        sb.AppendLine();

        sb.AppendLine(" * COMMANDS:");
        foreach (CommandInfo command in analysis.Commands)
        {
            sb.AppendLine($" *   {command.PropertyName}:");
            sb.AppendLine($" *     CanExecute References: [{string.Join(", ", command.CanExecuteReferences)}]");
            sb.AppendLine($" *     Binding Dependencies: [{string.Join(", ", command.DirectDependencies)}]");
        }

        sb.AppendLine();

        sb.AppendLine(" * TRANSITIVE DEPENDENCIES:");
        foreach (KeyValuePair<string, List<string>> kvp in analysis.TransitiveDependencies)
        {
            if (kvp.Value.Any())
            {
                sb.AppendLine($" *   {kvp.Key} depends on: [{string.Join(", ", kvp.Value)}]");
            }
        }

        sb.AppendLine();

        sb.AppendLine(" * NOTIFICATION REQUIREMENTS:");
        foreach (KeyValuePair<string, NotificationRequirements> kvp in analysis.NotificationRequirements)
        {
            NotificationRequirements req = kvp.Value;
            int totalNotifications = req.ComputedPropertyNotifications.Count +
                                     req.CommandNotifications.Count +
                                     req.CollectionDependentNotifications.Count;

            sb.AppendLine($" *   {kvp.Key} -> {totalNotifications} notifications:");

            if (req.ComputedPropertyNotifications.Any())
            {
                sb.AppendLine($" *     Computed: [{string.Join(", ", req.ComputedPropertyNotifications)}]");
            }

            if (req.CommandNotifications.Any())
            {
                sb.AppendLine($" *     Commands: [{string.Join(", ", req.CommandNotifications)}]");
            }

            if (req.CollectionDependentNotifications.Any())
            {
                sb.AppendLine($" *     Collections: [{string.Join(", ", req.CollectionDependentNotifications)}]");
            }
        }

        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine("// This debug information is only generated in DEBUG builds");
        sb.AppendLine("// and helps verify that the functional analysis is working correctly.");

        return sb.ToString();
    }
#endif
}