using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CdCSharp.Pangea.Binding.CodeGeneration;

[Generator]
public class ViewModelSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ViewModelAnalysis?> viewModelAnalyses = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsCandidateViewModel(s),
                static (ctx, _) => AnalyzeViewModel(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(viewModelAnalyses, static (spc, analysis) => GenerateCode(analysis, spc));
    }

    private static bool IsCandidateViewModel(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl &&
               (HasBindingFields(classDecl) || HasCommandProperties(classDecl));
    }

    private static bool HasBindingFields(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members.OfType<FieldDeclarationSyntax>()
            .Any(f => f.AttributeLists.Any(al => 
                al.Attributes.Any(a => a.Name.ToString().Contains("Binding"))));
    }

    private static bool HasCommandProperties(ClassDeclarationSyntax classDecl)
    {
        return classDecl.Members.OfType<PropertyDeclarationSyntax>()
            .Any(p => p.Type.ToString().Contains("RelayCommand"));
    }

    private static ViewModelAnalysis? AnalyzeViewModel(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclaration) return null;

        FunctionalAnalyzer analyzer = new FunctionalAnalyzer();
        return analyzer.AnalyzeViewModel(classDeclaration, context.SemanticModel);
    }

    private static void GenerateCode(ViewModelAnalysis? analysis, SourceProductionContext context)
    {
        if (analysis == null || analysis.BindingFields.Count == 0) return;

        string source = GenerateClassSource(analysis);
        context.AddSource($"{analysis.ClassName}.Binding.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateClassSource(ViewModelAnalysis analysis)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Pangea Binding Feature with Functional Analysis");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine();
        sb.AppendLine($"namespace {analysis.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {analysis.ClassName}");
        sb.AppendLine("{");

        // Generate properties with complete functional analysis
        foreach (BindingFieldInfo field in analysis.BindingFields)
        {
            GeneratePropertyWithFunctionalAnalysis(sb, field, analysis);
        }

        // Generate partial method declarations
        foreach (BindingFieldInfo field in analysis.BindingFields.Where(f => !f.ReadOnly))
            sb.AppendLine($"    partial void On{field.PropertyName}Changed();");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GeneratePropertyWithFunctionalAnalysis(StringBuilder sb, BindingFieldInfo field, ViewModelAnalysis analysis)
    {
        sb.AppendLine($"    public {field.FieldType} {field.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {field.FieldName};");

        if (!field.ReadOnly)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (SetProperty(ref {field.FieldName}, value))");
            sb.AppendLine("            {");
            sb.AppendLine($"                On{field.PropertyName}Changed();");

            // Get notification requirements from functional analysis
            if (analysis.NotificationRequirements.TryGetValue(field.PropertyName, out NotificationRequirements? requirements))
            {
                // Add computed property notifications
                foreach (string computedProp in requirements.ComputedPropertyNotifications)
                {
                    sb.AppendLine($"                OnPropertyChanged(nameof({computedProp}));");
                }

                // Add command notifications  
                foreach (string command in requirements.CommandNotifications)
                {
                    sb.AppendLine($"                {command}.RaiseCanExecuteChangedSafe();");
                }

                // Add collection-dependent notifications
                foreach (string collectionNotification in requirements.CollectionDependentNotifications)
                {
                    sb.AppendLine($"                OnPropertyChanged(nameof({collectionNotification}));");
                }
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }
}