using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CdCSharp.Pangea.Theming.CodeGeneration;

[Generator]
public class ThemeSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Detect classes with [Theme] attribute
        IncrementalValuesProvider<ThemeClassInfo?> themeClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsThemeClass(s),
                transform: static (ctx, _) => GetThemeClassInfo(ctx))
            .Where(static m => m != null);

        context.RegisterSourceOutput(themeClasses, static (spc, themeClass) => GenerateThemeCode(themeClass!, spc));
    }

    private static bool IsThemeClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl &&
               classDecl.AttributeLists.Count > 0 &&
               classDecl.AttributeLists
                   .SelectMany(al => al.Attributes)
                   .Any(attr => attr.Name.ToString().Contains("Theme"));
    }

    private static ThemeClassInfo? GetThemeClassInfo(GeneratorSyntaxContext context)
    {
        if (!(context.Node is ClassDeclarationSyntax classDeclaration))
            return null;

        SemanticModel semanticModel = context.SemanticModel;
        INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
        
        if (classSymbol == null)
            return null;

        // Check for [Theme] attribute
        AttributeData? themeAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name.Contains("Theme") == true);

        if (themeAttribute == null)
            return null;

        string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        string className = classSymbol.Name;

        // Find theme properties (properties with [ThemeProperty] attribute)
        List<ThemePropertyInfo> themeProperties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(prop => prop.GetAttributes()
                .Any(attr => attr.AttributeClass?.Name.Contains("ThemeProperty") == true))
            .Select(prop => new ThemePropertyInfo(
                prop.Name,
                prop.Type.ToDisplayString(),
                GetDefaultValue(prop)))
            .ToList();

        return new ThemeClassInfo(namespaceName, className, themeProperties);
    }

    private static string? GetDefaultValue(IPropertySymbol property)
    {
        // Extract default value from attribute or use type default
        AttributeData? themePropertyAttr = property.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name.Contains("ThemeProperty") == true);

        if (themePropertyAttr?.ConstructorArguments.Length > 0)
        {
            object? defaultValue = themePropertyAttr.ConstructorArguments[0].Value;
            return defaultValue?.ToString();
        }

        return null;
    }

    private static void GenerateThemeCode(ThemeClassInfo themeClass, SourceProductionContext context)
    {
        string source = GenerateThemeClassSource(themeClass);
        context.AddSource($"{themeClass.ClassName}.Theme.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateThemeClassSource(ThemeClassInfo themeClass)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Pangea Theming Feature");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Avalonia;");
        sb.AppendLine("using Avalonia.Data;");
        sb.AppendLine();
        sb.AppendLine($"namespace {themeClass.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    partial class {themeClass.ClassName}");
        sb.AppendLine("    {");

        // Generate styled properties
        foreach (ThemePropertyInfo? property in themeClass.Properties)
        {
            sb.AppendLine($"        public static readonly StyledProperty<{property.Type}> {property.Name}Property =");
            sb.AppendLine($"            AvaloniaProperty.Register<{themeClass.ClassName}, {property.Type}>(");
            sb.AppendLine($"                nameof({property.Name})");
            
            if (!string.IsNullOrEmpty(property.DefaultValue))
            {
                sb.AppendLine($"                , {property.DefaultValue}");
            }
            
            sb.AppendLine("            );");
            sb.AppendLine();

            // Generate CLR property
            sb.AppendLine($"        public {property.Type} {property.Name}");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => GetValue({property.Name}Property);");
            sb.AppendLine($"            set => SetValue({property.Name}Property, value);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

public class ThemeClassInfo
{
    public string Namespace { get; }
    public string ClassName { get; }
    public List<ThemePropertyInfo> Properties { get; }

    public ThemeClassInfo(string @namespace, string className, List<ThemePropertyInfo> properties)
    {
        Namespace = @namespace;
        ClassName = className;
        Properties = properties;
    }
}

public class ThemePropertyInfo
{
    public string Name { get; }
    public string Type { get; }
    public string? DefaultValue { get; }

    public ThemePropertyInfo(string name, string type, string? defaultValue)
    {
        Name = name;
        Type = type;
        DefaultValue = defaultValue;
    }
}