<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.9" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
<!--        <PackageReference Include="CdCSharp.Pangea" Version="1.1.0-pre.20250822204153" />-->
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\CdCSharp.Pangea.Binding.CodeGeneration\CdCSharp.Pangea.Binding.CodeGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

        <ProjectReference Include="..\..\src\CdCSharp.Pangea.Theming.CodeGeneration\CdCSharp.Pangea.Theming.CodeGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\..\src\CdCSharp.Pangea.Theming\CdCSharp.Pangea.Theming.csproj" />
      <ProjectReference Include="..\..\src\CdCSharp.Pangea\CdCSharp.Pangea.csproj" />
    </ItemGroup>
</Project>
