using System.Text;

namespace CdCSharp.Pangea.CodeGeneration;

/// <summary>Turns the model into the catalog class the runtime reads.</summary>
internal static class CatalogWriter
{
    internal static string Write(CatalogModel model)
    {
        StringBuilder source = new();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine($"namespace {CatalogTypes.CatalogNamespace}.{model.Identifier};");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine($"/// What '{model.AssemblyName}' contributes to Pangea startup, worked out while it was compiled.");
        source.AppendLine("/// </summary>");
        source.AppendLine("/// <remarks>");
        source.AppendLine("/// Generated by CdCSharp.Pangea.CodeGeneration. Every entry here is something the toolkit");
        source.AppendLine("/// would otherwise find by scanning assemblies at startup.");
        source.AppendLine("/// </remarks>");
        source.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"CdCSharp.Pangea.CodeGeneration\", \"1.0\")]");
        source.AppendLine($"public sealed class {CatalogTypes.CatalogTypeName} : global::CdCSharp.Pangea.Core.Abstractions.IPangeaCatalog");
        source.AppendLine("{");
        source.AppendLine($"    public string AssemblyName => \"{model.AssemblyName}\";");
        source.AppendLine();

        WriteFeatures(source, model);
        WriteViewModels(source, model);
        WriteViews(source, model);
        WriteNavigationRequests(source, model);
        WriteRegistration(source, model);

        source.AppendLine("}");

        return source.ToString();
    }

    private static void WriteFeatures(StringBuilder source, CatalogModel model)
    {
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::System.Func<global::CdCSharp.Pangea.Core.Abstractions.IPangeaFeature>> Features { get; } =");
        source.AppendLine("        new global::System.Func<global::CdCSharp.Pangea.Core.Abstractions.IPangeaFeature>[]");
        source.AppendLine("        {");

        foreach (FeatureModel feature in model.Features)
        {
            source.AppendLine($"            static () => new {feature.TypeName}(),");
        }

        source.AppendLine("        };");
        source.AppendLine();
    }

    private static void WriteViewModels(StringBuilder source, CatalogModel model)
    {
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::CdCSharp.Pangea.Core.Abstractions.PangeaViewModelEntry> ViewModels { get; } =");
        source.AppendLine("        new global::CdCSharp.Pangea.Core.Abstractions.PangeaViewModelEntry[]");
        source.AppendLine("        {");

        foreach (ViewModelModel viewModel in model.ViewModels)
        {
            source.AppendLine("            new global::CdCSharp.Pangea.Core.Abstractions.PangeaViewModelEntry(");
            source.AppendLine($"                typeof({viewModel.TypeName}), static sp => {viewModel.Factory}),");
        }

        source.AppendLine("        };");
        source.AppendLine();
    }

    private static void WriteViews(StringBuilder source, CatalogModel model)
    {
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::CdCSharp.Pangea.Core.Abstractions.PangeaViewEntry> Views { get; } =");
        source.AppendLine("        new global::CdCSharp.Pangea.Core.Abstractions.PangeaViewEntry[]");
        source.AppendLine("        {");

        foreach (ViewEntryModel view in model.Views)
        {
            source.AppendLine("            new global::CdCSharp.Pangea.Core.Abstractions.PangeaViewEntry(");
            source.AppendLine($"                \"{view.Name}\", typeof({view.TypeName}), static () => new {view.TypeName}()),");
        }

        source.AppendLine("        };");
        source.AppendLine();
    }

    private static void WriteNavigationRequests(StringBuilder source, CatalogModel model)
    {
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::CdCSharp.Pangea.Core.Abstractions.PangeaNavigationEntry> NavigationRequests { get; } =");
        source.AppendLine("        new global::CdCSharp.Pangea.Core.Abstractions.PangeaNavigationEntry[]");
        source.AppendLine("        {");

        foreach (NavigationModel request in model.NavigationRequests)
        {
            source.AppendLine("            new global::CdCSharp.Pangea.Core.Abstractions.PangeaNavigationEntry(");
            source.AppendLine($"                typeof({request.RequestTypeName}), typeof({request.DestinationTypeName})),");
        }

        source.AppendLine("        };");
        source.AppendLine();
    }

    /// <summary>
    /// Registers this catalog when the assembly is first touched, and touches the ones it
    /// references so none of them can be missed.
    /// </summary>
    private static void WriteRegistration(StringBuilder source, CatalogModel model)
    {
        source.AppendLine("    /// <summary>Registers this catalog. Safe to call more than once.</summary>");
        source.AppendLine("    public static void Ensure() =>");
        source.AppendLine($"        global::CdCSharp.Pangea.Core.Base.PangeaCatalogs.Add(new {CatalogTypes.CatalogTypeName}());");
        source.AppendLine();
        source.AppendLine("    /// <remarks>");
        source.AppendLine("    /// A module initializer runs when the assembly is first touched, which for a library of");
        source.AppendLine("    /// view models can be after startup has already asked what is in it. The referenced");
        source.AppendLine("    /// catalogs are touched from here so that cannot happen.");
        source.AppendLine("    /// </remarks>");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Register()");
        source.AppendLine("    {");
        source.AppendLine("        Ensure();");

        foreach (string referenced in model.ReferencedCatalogs)
        {
            source.AppendLine($"        {referenced}.Ensure();");
        }

        source.AppendLine("    }");
    }
}
